name: learn-github-actions
run-name: update ${{ github.actor }} resume site
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup environemnt
        working-directory: ./app
        run: npm install
      - name: build app
        working-directory: ./app
        run: npm run build && mv dist ../docs